### ISSUE TITLE
What is the best way to use test_construct in a before/setup block?

### ISSUE THREAD

**Issue by nicolasmccurdy** [bhb/test_construct#3]
With many test frameworks, it is often useful to specify code that runs before multiple examples. I am working on a project where I would like to use test_construct to clean up the messy filesystem code I am using to create some test directories and files before my examples are run.

However, it seems like this would not work properly, as `within_construct` would be called in the before block and end before my example runs, destroying the construct before I can test with it. Is there a workaround for this? I was thinking about calling `within_construct` in each of my examples and calling a helper method in each that would create the necessary directories, though that would still be a little repetitive.

__Note:__ If anyone has any ideas that would make this easier to do with test_construct, I would be happy to fork it and implement new features.

**Comment by bhb** [comment]
@nicolasmccurdy I hope the RSpec integration works for you. If not, please reopen this. Thanks for using the gem!

**Comment by programingnotes** [comment]
hi @bhb I am currently experiencing a situation similar to the explained by @nickmccurdy. 

```
describe '#create_domain_dir' do 
  context 'when directory does exist' do 
    before do 
      within_construct do |construct|
        @created_here = file_creator.create_domain_dir(domain_name)
      end
    end

    it 'returns said directory' do 
      within_construct do |construct|
        created = file_creator.create_domain_dir(domain_name)
        expect(created).to eq(@created_here)
      end
    end
  end
end
```

In your instructions you say to " use the RSpec integration and just make calls in 
your setup block" but doing this results in an error: 

```
RSpec::Core::ExampleGroup::WrongScopeError: `example` is not available from 
within an example (e.g. an `it` block) or from constructs that run in the scope of 
an example (e.g. `before`, `let`, etc). It is only available on an example group 
(e.g. a `describe` or `context` block).
``` 

I have looked through [rspec_integration](https://github.com/bhb/test_construct/blob/master/lib/test_construct/rspec_integration.rb) but can't seem to figure out how to accomplish keeping the construct around till my example block runs. 

Would appreciate feedback please. thank you!
